name: Benchmark.js Example
on:
  push:
    branches:
      - master
      - benchmark

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run JavaScript benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run benchmark
        run: npm install && npm i jest-standard-reporter && npm install --global jest@26.6.3 && npm install --global ts-jest@26.5.6 && npm run benchmarks | tee tests/benchmarks/output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark
          tool: "benchmarkjs"
          output-file-path: tests/benchmarks/output.txt
          github-token: ${{ secrets.ACCESS_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "150%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@roguib"
